---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: model-serving-default-mask-rcnn
  labels:
    type: dlib
    service: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      service: model-serving
      model: default-mask-rcnn
  template:
    metadata:
      labels:
        service: model-serving
        model: default-mask-rcnn
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: model-serving-default-mask-rcnn-pvc
      containers:
      - name: server
        image: asia.gcr.io/linker-aurora/mask-rcnn-serving:rc
        resources:
          requests:
            memory: 1Gi
        volumeMounts:
        - name: data-volume
          mountPath: /data
