---
apiVersion: v1
kind: Service
metadata:
  name: model-serving-default-mask-rcnn
  labels:
    type: dlib
    service: inference
spec:
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  selector:
    service: model-serving
    model: default-mask-rcnn